house_pricing:
  train_dataset: /Users/alicee/Desktop/Work_Main/spbu-ai-fundamentals/datasets/kaggle_house_prices/train.csv
  test_dataset: /Users/alicee/Desktop/Work_Main/spbu-ai-fundamentals/datasets/kaggle_house_prices/test.csv
classification:
  wdbc: /Users/alicee/Desktop/Work_Main/spbu-ai-fundamentals/datasets/wdbc/data.csv
  mushrooms: /Users/alicee/Desktop/Work_Main/spbu-ai-fundamentals/datasets/mushrooms.csv
clustering:
  flowcytometry: /Users/alicee/Desktop/Work_Main/spbu-ai-fundamentals/datasets/flowcytometry